services:
  postgres:
    image: postgres:16-alpine
    container_name: healthcare-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthcare_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=password psql -h localhost -U user -d healthcare_db -c 'SELECT 1;'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - healthcare-network


  # Python agent backend
  backend:
    build:
      context: ./agents
      dockerfile: Dockerfile
    container_name: healthcare-backend
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/healthcare_db
      # Add Google Gemini API Key
      GOOGLE_API_KEY: AIzaSyB1eMhEEOazSJ42ilYBz93Resk0JwNFrPw
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - healthcare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.setup
    container_name: healthcare-frontend
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/healthcare_db
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: your-secret-key-change-this-in-production
      BETTER_AUTH_URL: http://localhost:3000
      BETTER_AUTH_SECRET: your-better-auth-secret-change-this-in-production
      AGENT_BACKEND_URL: http://localhost:8000/agui
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - healthcare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:

networks:
  healthcare-network:
    driver: bridge
